[package]
name = "md-gateway"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
tokio-tungstenite = { workspace = true }
backoff = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
uuid = { workspace = true }

# Internal
exchange-adapter-lbank = { path = "../exchange-adapter-lbank" }

[dev-dependencies]
tokio = { workspace = true }
